name: Dev Branch

on:
  push:
    paths-ignore:
      - .github/workflows/**
      - 'README.md'
    branches:
      - dev

jobs:
  changes:
    runs-on: self-hosted
    container:
      image: reneruprecht/ci-node22
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          backend:
            - 'backend/**'
  backend-tests:
    needs: changes
    if: "${{ needs.changes.outputs.backend == 'true' }}"
    uses: ./.github/workflows/backend-tests.yml
    with:
      run_integration_tests: true
      upload_plan: true
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  # docker-build:
  #   needs: backend-tests
  #   uses: ./.github/workflows/docker-build.yml
  #   with:
  #     name: "alertbridge-backend"
  #     dockerfile: "docker/backend/Dockerfile"
  #   secrets:
  #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
