name: Dev Branch

on:
  push:
    paths-ignore:
      - .github/workflows/**
      - 'README.md'
    branches:
      - dev

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    with:
      run_integration_tests: true
      upload_plan: true
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  docker-build:
    needs: backend-tests
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "alertbridge-backend"
      dockerfile: "docker/backend/Dockerfile"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
