name: Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    with:
      run_integration_tests: true
      upload_plan: true
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
