name: Main Branch

on:
  push:
    paths-ignore:
      - .github/workflows/**
      - 'README.md'
    branches:
      - main

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    with:
      run_integration_tests: true
      upload_plan: true
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  docker-push:
    needs: backend-tests
    uses: ./.github/workflows/docker-push.yml
    with:
      name: "alertbridge-backend"
      dockerfile: "docker/backend/Dockerfile"
      push_latest: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
